FROM bahmniindiadistro/openmrs:latest

COPY bahmni-emr/resources/openhmis.backboneforms*.omod ${OPENMRS_APPLICATION_DATA_DIRECTORY}/modules/
COPY bahmni-emr/resources/openhmis.commons*.omod ${OPENMRS_APPLICATION_DATA_DIRECTORY}/modules/
COPY bahmni-emr/resources/openhmis.inventory*.omod ${OPENMRS_APPLICATION_DATA_DIRECTORY}/modules/
COPY bahmni-emr/resources/jasperreport*.omod ${OPENMRS_APPLICATION_DATA_DIRECTORY}/modules/


