#!/bin/bash
MYSQL_HOST=192.168.1.100
MYSQL_ROOT_USERNAME=root
MYSQL_ROOT_PASSWORD=rootPassword

OPENMRS_DB_NAME=openmrs
OPENMRS_DB_USERNAME=openmrs-user
OPENMRS_DB_PASSWORD=password

REPORTS_DB_NAME=bahmni_reports
REPORTS_DB_USERNAME=reports-user
REPORTS_DB_PASSWORD=password


echo "Creating OpenMRS Database"
mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $OPENMRS_DB_NAME;"
mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME -p$MYSQL_ROOT_PASSWORD -e "CREATE USER IF NOT EXISTS '$OPENMRS_DB_USERNAME'@'%' IDENTIFIED BY '$OPENMRS_DB_PASSWORD';"
mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON $OPENMRS_DB_NAME.* TO '$OPENMRS_DB_USERNAME'@'%';"
echo "Restoring OpenMRS Database"
gunzip -c ../backup_data/openmrs/openmrs_backup_29072023.sql.gz > ../backup_data/openmrs/openmrs_backup_29072023.sql
mysql -h $MYSQL_HOST -u $OPENMRS_DB_USERNAME -p$OPENMRS_DB_PASSWORD $OPENMRS_DB_NAME < ../backup_data/openmrs/openmrs_backup_29072023.sql

echo "Creating Bahmni Reports Database"
mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $REPORTS_DB_NAME;"
mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME -p$MYSQL_ROOT_PASSWORD -e "CREATE USER IF NOT EXISTS '$REPORTS_DB_USERNAME'@'%' IDENTIFIED BY '$REPORTS_DB_PASSWORD';"
mysql -h $MYSQL_HOST -u $MYSQL_ROOT_USERNAME -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON $REPORTS_DB_NAME.* TO '$REPORTS_DB_USERNAME'@'%';"
